### Shopping List API Test File
### For use with humao.rest-client VSCode extension
### Make sure the server is running: PROJECT_CONFIG_FILE=config/dev.json ./bin/api

@baseUrl = http://localhost:8080/api/v1
@familyName = Tank
@groceryListUUID = 20e5fa9d-aada-463c-8121-afac1c619ae5
@milkItemUUID = 29b50c1a-7cc7-4c2f-aac5-2c29fcba8cbc

### 1. Get all lists for a family (should be empty initially)
GET {{baseUrl}}/{{familyName}}

### 2. Create a new list for the family
POST {{baseUrl}}/{{familyName}}
Content-Type: application/json

{
    "name": "grocery",
    "display_name": "Grocery List"
}

### 5. Get all items on the grocery list (should be empty)
GET {{baseUrl}}/{{familyName}}/{{groceryListUUID}}

### 6. Add an item to the grocery list (using string)
POST {{baseUrl}}/{{familyName}}/{{groceryListUUID}}/milk

### 10. Get available items for the grocery list
GET {{baseUrl}}/{{familyName}}/{{groceryListUUID}}/items

### 15. Delete an item from grocery list (replace UUID with actual UUID from step 9)
# Note: You'll need to copy the UUID from the response in step 9
# DELETE {{baseUrl}}/{{familyName}}/grocery/REPLACE_WITH_ACTUAL_UUID

### Example delete (uncomment and replace UUID):
DELETE {{baseUrl}}/{{familyName}}/{{groceryListUUID}}/{{milkItemUUID}}
